spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          azure:
#            issuer-uri: https://login.microsoftonline.com/d556ae42-cb2c-4748-ad23-af960d0701f0/v2.0
#        registration:
#          azure-dev:
#            provider: azure
#            client-id: 'fe11e03e-781e-41cc-be42-f1594435c231'
#            client-secret: '.M48Q~3BEZAddmOXDwAhvaKN0ah8rJwDdypDPcMv'
#            scope:
#              - openid
#              - email
#              - profile

  datasource:
    url: 'jdbc:sqlserver://grd-poc6-admin-azuresql-db.database.windows.net:1433;database=grd-poc6-admin-azuresql-db;user=fe11e03e-781e-41cc-be42-f1594435c231;password=.M48Q~3BEZAddmOXDwAhvaKN0ah8rJwDdypDPcMv;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryServicePrincipal'
#    azure:
#      passwordless-enabled: true
#      credential:
#        client-id: 'fe11e03e-781e-41cc-be42-f1594435c231'
#        client-secret: '.M48Q~3BEZAddmOXDwAhvaKN0ah8rJwDdypDPcMv'


    hikari:
      jdbc-url: 'jdbc:sqlserver://grd-poc6-admin-azuresql-db.database.windows.net:1433;database=grd-poc6-admin-azuresql-db;user=fe11e03e-781e-41cc-be42-f1594435c231;password=.M48Q~3BEZAddmOXDwAhvaKN0ah8rJwDdypDPcMv;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryServicePrincipal'#

  sql:
    init:
      mode=always: always
  jpa:
    hibernate:
      ddl-auto: update


    show-sql: true

    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG

      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      enabled: true
      show-details: always

    info:
      enabled: true


  security:
    enabled: false
  port: 9000
